Задание 1

In [ ]:
import numpy as np

In [4]:
a = np.array([[1, 6],
             [2, 8],
             [3, 11],
             [3, 10],
             [1, 7]])

In [5]:
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [7]:
mean_a = a.mean(axis = 0)
mean_a

array([2. , 8.4])

Задание 2

In [8]:
a_centered = a-mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

Задание 3

In [9]:
a_centered_sp = a_centered.T[0] @ a_centered.T[1]
a_centered_sp

8.0

In [11]:
a_centered_sp / (a_centered.shape[0]-1)

2.0

Задание 4

In [12]:
np.cov(a.T)[0, 1]

2.0